An interactive dashboard was developed using Power BI to visualize and analyze contract data. The core dataset includes various business indicators, with columns identifying the country and a target label distinguishing fraudulent from non-fraudulent contracts. This dataset was built in Dataiku, with the full data pipeline available in the BI Zone. A Python recipe processes the input dataset indicators_all_countries to generate the INDICATORS_BI output by standardizing unclear column names for improved readability.

Given the dataset's size—approximately 3 million contracts—a random sample of 100,000 non-fraudulent contracts is extracted to reduce noise and mitigate the impact of outliers. This sampling step preserves the overall distribution and ensures better performance and interpretability in Power BI.

Once indicators_all_indicators is generated, it is imported into Power BI, where several transformations are applied. Negative financial values are replaced with nulls to avoid skewing statistical measures such as averages and medians. Columns originally labeled in French, German, or Italian—such as payment methods—are translated into English. Additionally, unnecessary columns are removed to streamline the dataset.

One key area for improvement involves translating large categorical columns such as client activity and leased material. Due to the volume (thousands of unique values) and Dataiku's offline Python environment—limiting access to translation APIs—automated translation was not feasible. Manual translation was also impractical given the time constraints and scale of the data.

To update the dashboard, the indicators_all_countries recipe must be re-executed in Dataiku. The output dataset INDICATORS_BI_SAMPLED should then be reloaded into Power BI by updating the data source via Power Query.
